export const SET_REGISTER = 'SET_REGISTER';

export const SET_STACK = 'SET_STACK';

export const SET_CONSOLE_OUTPUT = 'SET_CONSOLE_OUTPUT';

export const SET_CONSOLE_INSTRUCTION = 'SET_CONSOLE_INSTRUCTION';